version: '3.8'

services:
  produto-service:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: comprae-produto-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://comprae-postgres-produto:5432/comprae_produtos
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    ports:
      - "8081:8080"
    networks:
      - comprae-network

networks:
  comprae-network:
    external: true
