# ===================================================
# CONFIGURAÇÕES DO CLIENTE DE CONFIGURAÇÃO COMPRAÊ - DOCKER
# ===================================================

# Configurações do Config Server para ambiente Docker
config.client.server-url=http://comprae-config-server:8080
config.client.environment=docker

# Configurações do Kafka para ambiente Docker
config.client.kafka.bootstrap-servers=kafka:9092