# ===================================================
# CONFIGURAÇÕES DO CLIENTE DE CONFIGURAÇÃO COMPRAÊ - DESENVOLVIMENTO LOCAL
# ===================================================

# Configurações do Config Server para ambiente local
config.client.server-url=http://localhost:8080
config.client.environment=dev

# Configurações do Kafka para ambiente local
config.client.kafka.bootstrap-servers=localhost:9092